name: Continuous Integration - Backend & Frontend

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"
      - "frontend/**"

  pull_request:
    branches:
      - master
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect backend changes
        id: backend-changes
        uses: tj-actions/changed-files@v45
        with:
          files: backend/**

      - name: Detect frontend changes
        id: frontend-changes
        uses: tj-actions/changed-files@v45
        with:
          files: frontend/**

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Install dependencies (from workspace root)
        run: pnpm install

      - name: Generate Prisma Client
        if: steps.backend-changes.outputs.any_changed == 'true'
        run: pnpm --filter backend exec prisma generate

      - name: Lint and Build Backend
        if: steps.backend-changes.outputs.any_changed == 'true'
        run: |
          pnpm --filter backend lint
          pnpm --filter backend build

      - name: Lint and Build Frontend
        if: steps.frontend-changes.outputs.any_changed == 'true'
        run: |
          pnpm --filter frontend lint
          pnpm --filter frontend build
